#!/bin/sh
docker stop breakfastbot_app
docker rm breakfastbot_app

# ensure we are in git root for build
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT" && docker build . -f deploy/app/Dockerfile -t breakfastbot

docker create \
  --name breakfastbot_app \
  --restart=always \
  --network localnet \
  -v "$ROOT"/prod-config.edn:/breakfastbot/prod-config.edn \
  --init \
  breakfastbot

docker restart breakfastbot_app
