create table if not exists members (
  id int primary key generated by default as identity,
  email text unique,
  fullname varchar(40),
  active boolean not null
);

create table if not exists attendances (
  day date,
  id integer references members(id),
  primary key (day, id)
);

create table if not exists bringer (
  day date unique,
  id integer references members(id),
  primary key (day, id),
  foreign key (day, id) references attendances (day, id)
);

create table if not exists app_state (
  dummy integer primary key,
  attendance_primed_until date not null
);

create table if not exists migratus (id BIGINT);
